TARGET  = db_proxy
SRC     = init.c db_proxy.c
OBJ     = $(SRC:.c=.o)
DEFS    = -D_REENTRANT  -D_POSIX_PTHREAD_SEMANTICS -D_GNU_SOURCE -D_DEBUG
INC     = -I./lib
LIBS    = -L/usr/lib64/mysql -lmysqlclient -lnsl -L./lib -lcmpp
CFLAGS  = -g -Wall -fPIC $(INC) $(DEFS) 
SHARED  = -shared -o

${TARGET}:
	gcc ${CFLAGS} -o ${TARGET} ${SRC} ${LIBS}
${OBJ}: ${SRC}
	gcc ${CFLAGS} -c ${SRC}
clean:
	rm -f core ${TARGET} ${OBJ}
